"""Builds an AVL .avl geometry input file (text) from a design vector.

Horizontal/vertical tail sections deliberately omit an airfoil (NACA/AFIL) card: an AVL
SECTION with no camber/thickness data *is* a zero-thickness flat plate at the given incidence,
which is exactly the assignment's "flat plate" tail assumption -- no special-casing needed.
"""
from __future__ import annotations

import math

from avlnn.config import Constants
from avlnn.derived import AircraftGeometry, assemble

_AVL_NCHORD = 8
_AVL_NSPAN_WING = 20
_AVL_NSPAN_TAIL = 12


def _naca_digits(section_name: str) -> str:
    digits = "".join(ch for ch in section_name if ch.isdigit())
    if len(digits) != 4:
        raise ValueError(f"expected a NACA 4-digit section, got {section_name!r}")
    return digits


def _control_card(name: str, hinge_frac: float, hinge_axis: str, sgn_dup: float) -> str:
    return f"CONTROL\n{name}   1.0   {hinge_frac:.4f}   {hinge_axis}   {sgn_dup:.1f}\n"


def _wing_surface(design: dict[str, float], geom: AircraftGeometry, c: Constants) -> str:
    wing = geom.wing
    naca = _naca_digits(c.airfoil.wing_section)
    x_root = design["wing_root_le_x_b_m"]
    inc = design["wing_incidence_deg"]

    aileron_y0 = (wing.span_m / 2.0) * design["aileron_span_start_frac"]
    aileron_chord_frac_at_tip = design["aileron_chord_frac"]
    # aileron hinge at (1 - chord_frac) of local chord, i.e. hinge line is that far aft of LE
    aileron_hinge = 1.0 - aileron_chord_frac_at_tip

    lines = [
        "SURFACE",
        "Wing",
        f"{_AVL_NCHORD}   1.0   {_AVL_NSPAN_WING}   -2.0",
        "YDUPLICATE",
        "0.0",
        "",
        "SECTION",
        f"{x_root:.5f}  0.0  0.0  {wing.root_chord_m:.5f}  {inc:.4f}",
        "NACA",
        naca,
        "",
        "SECTION",
        f"{x_root + aileron_y0 * math.tan(wing.le_sweep_rad):.5f}  {aileron_y0:.5f}  "
        f"{aileron_y0 * math.tan(math.radians(design['wing_dihedral_deg'])):.5f}  "
        f"{wing.root_chord_m + (wing.tip_chord_m - wing.root_chord_m) * (2 * aileron_y0 / wing.span_m):.5f}  "
        f"{inc:.4f}",
        "NACA",
        naca,
        _control_card("aileron", aileron_hinge, "0. 0. 0.", -1.0),
        "SECTION",
        f"{x_root + wing.tip_x_offset_m:.5f}  {wing.span_m / 2.0:.5f}  {wing.tip_z_offset_m:.5f}  "
        f"{wing.tip_chord_m:.5f}  {inc:.4f}",
        "NACA",
        naca,
        _control_card("aileron", aileron_hinge, "0. 0. 0.", -1.0),
        "",
    ]
    return "\n".join(lines)


def _htail_surface(design: dict[str, float], geom: AircraftGeometry, c: Constants) -> str:
    tail = geom.htail
    hinge = c.tail.hinge_chord_frac
    lines = [
        "SURFACE",
        "Horizontal Tail",
        f"{_AVL_NCHORD}   1.0   {_AVL_NSPAN_TAIL}   -1.5",
        "YDUPLICATE",
        "0.0",
        "",
        "SECTION",
        f"{tail.root_le_x_b_m:.5f}  0.0  0.0  {tail.root_chord_m:.5f}  0.0",
        _control_card("elevator", hinge, "0. 1. 0.", 1.0),
        "SECTION",
        f"{tail.root_le_x_b_m + tail.tip_x_offset_m:.5f}  {tail.span_m / 2.0:.5f}  0.0  "
        f"{tail.root_chord_m:.5f}  0.0",
        _control_card("elevator", hinge, "0. 1. 0.", 1.0),
        "",
    ]
    return "\n".join(lines)


def _vtail_surface(design: dict[str, float], geom: AircraftGeometry, c: Constants) -> str:
    tail = geom.vtail
    hinge = c.tail.hinge_chord_frac
    lines = [
        "SURFACE",
        "Vertical Tail",
        f"{_AVL_NCHORD}   1.0   {_AVL_NSPAN_TAIL}   1.0",
        "",
        "SECTION",
        f"{tail.root_le_x_b_m:.5f}  0.0  0.0  {tail.root_chord_m:.5f}  0.0",
        _control_card("rudder", hinge, "0. 0. 1.", 1.0),
        "SECTION",
        f"{tail.root_le_x_b_m + tail.tip_x_offset_m:.5f}  0.0  {tail.span_m:.5f}  "
        f"{tail.root_chord_m:.5f}  0.0",
        _control_card("rudder", hinge, "0. 0. 1.", 1.0),
        "",
    ]
    return "\n".join(lines)


def build_avl_geometry(design: dict[str, float], c: Constants) -> tuple[str, AircraftGeometry]:
    """Returns (avl_file_text, resolved_geometry). `resolved_geometry` is reused by
    massfile.py and runcase.py so mass placement and trim conditions stay consistent."""
    geom = assemble(design, c)

    header = "\n".join([
        "Jet Trainer (auto-generated by avlnn.geometry)",
        "#Mach",
        "0.0",
        "#IYsym  IZsym  Zsym",
        "0      0      0.0",
        "#Sref   Cref   Bref",
        f"{geom.sref_m2:.5f}  {geom.cref_m:.5f}  {geom.bref_m:.5f}",
        "#Xref   Yref   Zref",
        f"{geom.x_cg_b_m:.5f}  0.0  0.0",
        "",
    ])

    body = "\n".join([
        _wing_surface(design, geom, c),
        _htail_surface(design, geom, c),
        _vtail_surface(design, geom, c),
    ])

    return header + body, geom
