"""Builds an AVL .mass file from a design vector: the fixed 20-point fuselage grid plus the
two wing point masses, exactly per the assignment's mass-distribution spec."""
from __future__ import annotations

from avlnn.atmosphere import isa
from avlnn.config import Constants
from avlnn.derived import AircraftGeometry


def _fuselage_points(design: dict[str, float], c: Constants) -> list[tuple[float, float, float, float]]:
    m = c.mass
    spacing = design["fuselage_row_spacing_m"]
    d4 = m.d_fuse_m / 4.0
    points = []
    for row in range(m.fuselage_n_rows):
        x = (row - m.fuselage_mid_row_index) * spacing
        for y_sign in (+1.0, -1.0):
            for z_sign in (+1.0, -1.0):
                points.append((m.fuselage_point_mass_kg, x, y_sign * d4, z_sign * d4))
    return points


def _wing_points(
    design: dict[str, float], geom: AircraftGeometry, c: Constants,
) -> list[tuple[float, float, float, float]]:
    wing_mass = c.mass.wing_fraction_each * c.mass.total_kg
    x = design["wing_root_le_x_b_m"] + geom.wing.mass_point_x_b_m
    y = geom.wing.mass_point_y_m
    return [(wing_mass, x, +y, 0.0), (wing_mass, x, -y, 0.0)]


def build_avl_mass_file(design: dict[str, float], geom: AircraftGeometry, c: Constants) -> str:
    points = _fuselage_points(design, c) + _wing_points(design, geom, c)
    total = sum(p[0] for p in points)
    expected = c.mass.total_kg
    if abs(total - expected) > 1e-6 * expected:
        raise ValueError(f"mass file totals {total:.3f} kg, expected {expected:.3f} kg")

    # MSET applies this g and rho to the run cases, OVERRIDING the .run file's density --
    # so rho here must be the CRUISE density, not sea level, or every eigenmode analysis
    # runs with ~3.4x too much aerodynamic damping (verified against a live AVL 3.52
    # session on 2026-07-19: the MODE parameter table showed the mass-file rho).
    atm_cruise = isa(c.mission.altitude_cruise_m, c.atmosphere)
    lines = [
        "# Auto-generated by avlnn.massfile -- do not edit by hand",
        "Lunit = 1.0 m",
        "Munit = 1.0 kg",
        "Tunit = 1.0 s",
        "",
        f"g   = {c.atmosphere.g0_m_s2}",
        f"rho = {atm_cruise.density_kg_m3:.5f}",
        "",
        "#  mass      x         y         z        Ixx  Iyy  Izz  Ixy  Ixz  Iyz",
    ]
    for mass, x, y, z in points:
        lines.append(
            f"   {mass:10.4f}  {x:9.5f}  {y:9.5f}  {z:9.5f}"
            f"   0.0  0.0  0.0  0.0  0.0  0.0"
        )
    lines.append("")
    return "\n".join(lines)
