 ---------------------------------------------
 Run case  1:   Cruise

 alpha        ->  CL          =   0.84419
 beta         ->  beta        =   0.00000
 pb/2V        ->  pb/2V       =   0.00000
 qc/2V        ->  qc/2V       =   0.00000
 rb/2V        ->  rb/2V       =   0.00000
 aileron      ->  aileron     =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  rudder      =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.00000
 qc/2V     =   0.00000
 rb/2V     =   0.00000
 CL        =   0.84419
 CDo       =   0.03000
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.500
 velocity  =   147.53475     m/s
 density   =   0.36392     kg/m^3
 grav.acc. =   9.80665     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   1.00000
 X_cg      =   -0.11197     Lunit
 Y_cg      =   0.00000     Lunit
 Z_cg      =   0.00000     Lunit
