#!/usr/bin/env python3
"""CLI: train the NN surrogate on a dataset generated by run_dataset_gen.py.

Usage:
    python scripts/train_surrogate.py --dataset data/dataset.csv --out data/surrogate.pt
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from avlnn.design_space import DesignSpace  # noqa: E402
from avlnn.surrogate.dataset import load_dataset  # noqa: E402
from avlnn.surrogate.model import train_surrogate  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", type=Path, default=REPO_ROOT / "data" / "dataset.csv")
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "data" / "surrogate.pt")
    parser.add_argument("--epochs", type=int, default=300)
    args = parser.parse_args()

    space = DesignSpace.load()
    df = load_dataset(args.dataset)
    bundle, metrics = train_surrogate(df, space, epochs=args.epochs)
    bundle.save(args.out)

    print(f"Trained on {int(metrics['n_train'])} samples, validated on {int(metrics['n_val'])}")
    print(f"Validation MSE (normalized outputs): {metrics['val_mse']:.5f}")
    print(f"Saved surrogate -> {args.out}")


if __name__ == "__main__":
    main()
